### ISSUE TITLE
Cut down dependencies

### ISSUE THREAD

**Issue by miohtama** [websauna/websauna#37]
Currently IPython is pulling in tons of dependencies which might or might not be useful.

Many users find this as extra truckload of crap.

Make IPython installation optional and have graceful errors telling users "no you cannot use autocomplete shell" if IPython is not installed.

**Comment by miohtama** [comment]
See http://stackoverflow.com/questions/36941264/negative-extra-requires-in-python-setup-py

**Comment by enkidulan** [comment]
I believe that jupyter notebook and ipython should be moved out of websauna at all into separate package, the reasons for these are:
   1. jupyter notebook is a black hole in security that allows any kind of injection including command injection.
   2. it make deployment of simple servises much harder because of tons heavy dependencies that notebook brings.

Actually while playing around websauna I tried to move jupyter notebook out into websauna.notebook package and mainly succeeded in it. The parts that are left to hadle are:
  * ACL for `shell` needs to be moved out from websauna
  * `show shell` button registering on resource context shoud be moved out as well
  * move out from websauna the main nav bar link to shell

But that is kind of tricky part for me. Probably I'm not doing it right way, but the things that I'm dealing now are: 
  * websauna seems to not allow to add new nav items dynamically, the only way is to override template as described in https://websauna.org/docs/narrative/frontend/templates.html#customizing-navigation but for addons it seems not to be a good approach.  
  * not clear if websaune allows adding resource buttons into non-overriding way. The way that is described here https://websauna.org/docs/narrative/crud/crud.html#resource-buttons doesn't seem to be a good choice for addons. Not sure if I got it right, but another way described in  https://websauna.org/docs/api/websauna.system.admin.menu.html?highlight=routeentry#websauna.system.admin.menu.Entry  didn't work for me either, but still I'm not sure if I got right how to use it. The Menu class method seems to referring to not existing template https://github.com/websauna/websauna/blob/master/websauna/system/admin/menu.py#L18.

Probably after I digin a bit more I'll create issues for things that is not clear to me. The progress that I have so far with moving notebook out from websauna is here https://github.com/enkidulan/websauna and here https://github.com/enkidulan/websauna.notebook.

BTW, is there any package management systems that have `exclude` (negative extra requires) option?

**Comment by miohtama** [comment]
Thanks for the good feedback!

I'll hope to move IPython to a separate dependency this weekend.

**Comment by miohtama** [comment]
For buttons the long term plan is to move from hardcoded slots to pyramid_layout panels, so that addons can easily contribute there.

**Comment by enkidulan** [comment]
:beer pyramid_layout seems to be a cool thing. I hope my changes would be helpful at some point, unfortunately I haven't got  any time to get my changes to the good point this week.... anyway let me know if I can assist with that :)

**Comment by enkidulan** [comment]
I guess I've done with moving notebook out form websauna, what I wasn't able to achieve are:
* adding 'shell' link to main nav-bar. Probably make sense to do it dynamically after integrating pyramid layout. 
* I left acl's entries `(Allow, 'superuser:superuser', 'shell')` because I thing that is a good permision to have in a system and which may be used by other addons as well. 

What was done:
* moved all shell related registrations and logic into 'websauna.notebook' package 
* made `shell link` to apped on UserAdmin.Resource, by quite dirty hack https://github.com/enkidulan/websauna.notebook/blob/master/websauna/notebook/subscribers.py#L11.
There is also left some very trivial thing to do: move dependencies list, clean up 'websauna.notebook' package, add license to it, etc... 
@miohtama, if you are Okey with that course of changes I will create a PR.

**Comment by miohtama** [comment]
@enkidulan Can you open a pull request any case? I'll pick where you left.

I am going to have "features" system ready which allows you to control links contributed by addons, and various other aspects later this week.

**Comment by miohtama** [comment]
@enkidulan Fixed in 56a41b0a473d0c83c435251a82ff8e490ff73ddf
